apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: pod-delete-trigger
                namespace: argo
              spec:
                serviceAccountName: falco-pod-delete
                entrypoint: delete-pod
                arguments:
                  parameters:
                    - name: falco_event
                      # the value will get overridden by event payload from test-dep
                      value: "{}"
                templates:
                  - name: delete-pod
                    inputs:
                      parameters:
                        - name: falco_event
                    container:
                      image: devopps/kubernetes-response-engine-based-on-event-driven-workflow@sha256:22ee203a33fe88f0f99968daebdcea0ca52c8a3d6f7af4c823ed78ac15b7c5db
                      env:
                        - name: BODY
                          value: "{{inputs.parameters.falco_event}}"
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value
